    roman = ''
    while num // 1000 != 0:
        roman += 'M'
        num -= 1000
    if num >= 900:
        roman += 'CM'
        numn -= 900
    while num // 500 != 0:
        roman += 'D'
        num -= 500
    if num >= 400:
        roman += 'CD'
        numn -= 400
    while num // 100 != 0:
        roman += 'C'
        num -= 100
    if num >= 90:
        roman += 'XC'
        numn -= 90
    while num // 50 != 0:
        roman += 'L'
        num -= 50
    if num >= 40:
        roman += 'XL'
        numn -= 40
    while num // 10 != 0:
        roman += 'X'
        num -= 10
    if num >= 9:
        roman += 'IX'
        numn -= 9
    while num // 5 != 0:
        roman += 'V'
        num -= 5
    if num >= 4:
        roman += 'IV'
        numn -= 4
    while num // 1 != 0:
        roman += 'I'
        num -= 1
    return roman